#!/usr/bin/env bash
ROS_SBCL_PATH=`rospack find sbcl`
export ROSLISP_PATH=`rospack find roslisp`
if [ -z "$ROSLISP_PATH" ]; then
  echo "roslisp not found"
  exit 1
fi

if [ -n "$ROS_SBCL_PATH" ]; then
  SBCL=/scripts/run-sbcl.sh
else
  SBCL=sbcl
fi

$SBCL --noinform --disable-debugger --load $ROSLISP_PATH/scripts/roslisp-sbcl-init --script $PACKAGE/scripts/$2

